name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: dependencies-${{ hashFiles('package.json') }}
          restore-keys: dependencies-

      - name: Cache example dependencies
        uses: actions/cache@v2
        with:
          path: example/node_modules
          key: dependencies-example-${{ hashFiles('example/package.json') }}
          restore-keys: dependencies-example-

      - name: Install dependencies
        run: |
          yarn install --cwd example --frozen-lockfile
          yarn install --frozen-lockfile

      - name: Lint files
        run: |
          yarn lint

      - name: Typecheck files
        run: |
          yarn typescript

      - name: Run unit tests
        run: |
          yarn test --coverage

      - name: Store coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage

      - name: Build package
        run: |
          yarn prepare
